### PR TITLE
Add address banning

### PR DESCRIPTION
**Pull request by sudeepb02**

### CODE REVIEW

**Comment by funkypenguin** [comment]
This is a WIP, @sudeepb02 is waiting on me (and a daemon sync) to test. I expect more changes are required before this is ready for action.

@sudeepb02, could you please turn this into a PR against https://github.com/funkypenguin/turtle-pool/tree/address-banning instead? That way I can test with my automated docker build pipeline before we submit PR to upstream :)

**Comment by SoreGums** [comment]
ok - cool - thanks for the extra info ;)

**Comment by sudeepb02** [comment]
Can someone please review the changes

**Comment by RocksteadyTC** [comment]
image

**Comment by sudeepb02** [comment]
IPC calls added.

**Comment by brandonlehmann** [comment]
@sudeepb02 This PR has been hanging out here with conflicts for over a month. I'm closing the PR. If you'd like to rebase and fix your branch and PR again we welcome the changes.

**Pull request closed without merging**
