### PR TITLE
nodejs v10.x upgrade

### PR DESCRIPTION
**Pull request by cryptoBOOOOM**

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
Is that all?

**Comment by cryptoBOOOOM** [comment]
yeah just some small fixes
for example "exit" needs to be "process.exit()" and stuff like that. Also fs.appendFile needed a callback

**Comment by cryptoBOOOOM** [comment]
i removed the nodejs there because of that i would install the old v0.10x there. need to install manually, referr to the nodejs install instructions i updated the link

**Comment by cryptoBOOOOM** [comment]
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by RocksteadyTC** [comment]
I'll add explicit instructions for NVM later

**Pull request merged**
